### ISSUE TITLE
BUG: If macro is not found app continues without error message

### ISSUE THREAD

**Issue by wiegraebe** [aics-int/microscope_automation#29]
- [ ] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the latest version of microscope_automation.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

## Description
If connect_zen_blue.run_macro does not find a macro (e.g. macro not defined in ZEN blue) nothing happens and the macro execution is skipped without error message.
In the case `self.Zen.Application.RunMacro(macro_name)` returns 'Macro \'10x_stitch\' not found'.

## Expected Behavior
User has the option to

- cancel execution of app
- change name of macro
- create macro in ZEN blue

## Reproduction
Use for experiment RunMacro in preferences the setting:

```
RunMacro:
  FunctionName: run_macro                       # Name of function in Python code in module microscopeAutomation that will process this experiment
  MacroName: 10x_stitch                         # Name of macro called in Zen Blue software
  Folder: ['10XwellScan\TapeOnly\split', '100X_zstack_2hr\TapeOnly', '100X_zstack_4hr\TapeOnly', '100X_zstack_24hr\TapeOnly'] # List of folders inside daily foder to create before running macro if they do not exist.
  Experiment: NoExperiment
```

and do not define a macro of this name in ZEN blue.

## Your code here

```
   def run_macro(self, macro_name, macro_param=None):
        """Function to run a given Zen Blue Macro

        Input:
         macro_name: Name of the macro

        Output:
         none
        """
        try:
            if macro_param is None:

                self.Zen.Application.RunMacro(macro_name)
            else:
                self.Zen.Application.RunMacro_2(macro_name, macro_param)

        except Exception as e:
            log(e)
            raise e

```

## Environment
*Any additional information about your environment*
